baseurl: ''
url: 'https://crytomodeler.app'
name: CryptoModeler App
author: Josep Roure
# email: info@cryptomodeler.app
title: Cryptomodeler App
# yotube: Add your youtube channel
# facebook: Add your facebook fanpage
# instagram: Add your instagram profile
# whatsapp: Add your whatsapp
# tel: Add your phone number

permalink: pretty

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

plugins:
    - jekyll-feed
    - jekyll-sitemap

exclude:
- README.md

cta:
  en: With our app you will finally be able to invest in cryptocurrencies without the risk of losing all your savings. Program it easily and take advantage of its actions in your favor.
  es: Con nuestra app podrás por fin invertir en criptodivisas sin el riesgo de perder todos tus ahorros. Prográmala fácilmente y aprovecha sus acciones a tu favor

cta-button:
  en: Download Crypto Modeler
  es: Descargar Crypto Modeler

h2-search:
  en: Find your favorite topic here
  es: Encuentra tu tema favorito aquí

nav-home:
  en: Home
  es: Inicio

nav-news:
  en: News
  es: Noticias

nav-pricing:
  en: Pricing
  es: Precios

nav-contact:
  en: Contact
  es: Contacto

footer-links:
  en: Our links
  es: Enlaces

footer-news:
  en: News
  es: Noticias

footer-pricing:
  en: Pricing
  es: Precios

footer-contact:
  en: Contact
  es: Contacto

footer-disclaimer:
  en: Disclaimer
  es: Descargos

footer-chat:
  en: Write Us
  es: Escríbenos

footer-down:
  en: Download your CryptoModeler App
  es: Descarga tu app de CryptoModeler

footer-register:
  en: 'Crypto Modeler - All rights reserved'
  es: 'Crypto Modeler - Todos los derechos reservados'

form-name:
  en: Name
  es: Nombre

form-email:
  en: Email
  es: Correo

form-write:
  en: Write your message
  es: Escribe tu mensaje

form-button:
  en: Say hello!
  es: Saluda!

article-share:
  en: Do you enjoy this article? Please, share it
  es: ¿Te gustó este artículo? Por favor, compártelo

article-more:
  en: Learn more about...
  es: Aprende más...

article-end:
  en: You do not have your Crypto Modeler app yet?
  es: ¿Todavía no instalas Crypto Modeler?

article-end-button:
  en: Download your app
  es: Descarga tu app